# Configuration Pre-commit pour LCPI-CLI
# Outils de qualité du code et de sécurité

repos:
  # Hooks de base pour la qualité du code
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      # Vérifications de base
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: debug-statements
      - id: name-tests-test
      - id: requirements-txt-fixer
      
  # Formatage du code Python
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        language_version: python3
        args: [--line-length=88, --target-version=py38]
        
  # Tri des imports
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: [--profile=black, --line-length=88]
        
  # Linting avec flake8
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args: [--max-line-length=88, --extend-ignore=E203,W503]
        additional_dependencies: [flake8-docstrings]
        
  # Vérification des types avec mypy
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        additional_dependencies: [types-all]
        args: [--ignore-missing-imports, --no-strict-optional]
        
  # Vérification de sécurité
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        args: [-r, src/, -f, json, -o, bandit-report.json]
        exclude: tests/
        
  # Vérification des vulnérabilités des dépendances
  - repo: https://github.com/PyCQA/safety
    rev: 2.3.5
    hooks:
      - id: safety
        args: [check, --json, --output, safety-report.json]
        
  # Vérification des licences
  - repo: https://github.com/apache/skywalking-eyes
    rev: v0.2.1
    hooks:
      - id: license-eye
        args: [header, fix]
        
  # Vérification des fichiers de configuration
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: check-xml
      
  # Vérification des fichiers de documentation
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-markdown
      - id: check-case-conflict
      - id: check-merge-conflict
      
  # Vérification des scripts shell
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-shellcheck
      - id: shellcheck
        args: [--severity=warning]
        
  # Vérification des fichiers de configuration CI/CD
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
        files: \.(yaml|yml)$
        exclude: |
          (?x)^(
              \.pre-commit-config\.yaml|
              .*\.template\.yaml|
              .*\.example\.yaml
          )$
          
  # Vérification des fichiers de test
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: name-tests-test
      - id: check-added-large-files
        args: [--maxkb=1000]
        
  # Vérification des fichiers de données
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
        files: \.(yaml|yml)$
        exclude: |
          (?x)^(
              \.pre-commit-config\.yaml|
              .*\.template\.yaml|
              .*\.example\.yaml
          )$

# Configuration globale
default_language_version:
  python: python3.8

# Configuration des hooks
ci:
  autofix_commit_msg: "style: auto-fix pre-commit hooks"
  autoupdate_commit_msg: "ci: pre-commit autoupdate"

# Configuration des exclusions
exclude: |
  (?x)^(
      \.git/|
      \.venv/|
      venv/|
      env/|
      __pycache__/|
      \.pytest_cache/|
      \.mypy_cache/|
      build/|
      dist/|
      \.eggs/|
      \.tox/|
      \.coverage|
      coverage\.xml|
      \.cache/|
      node_modules/|
      \.next/|
      \.nuxt/|
      \.output/|
      \.temp/|
      \.tmp/
  )$
