[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "lcpi-cli"
version = "2.1.0"
requires-python = ">=3.8"
dependencies = [
    "typer[all]", "PyYAML", "pandas", "matplotlib", "reportlab", "scipy"
]

[project.scripts]
lcpi = "lcpi.main:app"

[tool.typer]
name = "lcpi"
help = "LCPI-CLI - Plateforme de Calcul Polyvalent pour l'Ingénierie"
add_completion = true

[tool.setuptools]
package-dir = {"" = "src"}
packages = ["lcpi", "lcpi.utils"]
