# Configuration du projet LCPI
projet:
  nom: "projet_cm"
  version: "1.0.0"
  date_creation: "2025-08-01"
  description: "Projet d'ingénierie utilisant LCPI-CLI"

plugins_actifs:
  - cm

parametres_globaux:
  unite_longueur: "m"
  unite_force: "kN"
  unite_contrainte: "MPa"
  langue: "fr"

chemins:
  data: "./data"
  output: "./output"
  reports: "./reports"
  templates: "./templates"
